import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UIProviders } from "../providers/uiProvider";
import { SessionProviders } from "../providers/sessionProvider";
import { Suspense } from "react";
import Nav from "../ui/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {

  return (
    <html lang="en" className='dark'>
        <body className={inter.className}>
          <UIProviders>
          <SessionProviders>
            <Suspense>
              <Nav />
            </Suspense>
            {children}
          </SessionProviders>
          </UIProviders>
        </body>
    </html>
  );
}
